### PR TITLE
Adds multiselect to event type filter and fixes combobox duplications

### LINKED ISSUE #154: Fix the comboboxes on the timeline page
There are duplicates in the Event Type filter and Time scale options that need to be removed.

The time scale option has 2 hours options.

The Event Type filter re-adds the filter options every time you click on it.

### PR DESCRIPTION
**Pull request by klaki892**
- Adds the ability to multiselect eventTypes via the UI
- Fixes bug in event type where options would be duplicated upon opening
- fixes duplicate "hours" in timeline scaling combobox

Resolves #154

### CODE REVIEW

File: WPF/SeeShells/SeeShells/UI/EventFilters/EventNameFilter.cs [hunk 1]
```diff
@@ -19,7 +19,7 @@ public class EventNameFilter : INodeFilter
         /// Filter's <see cref="IEvent"/>s by their <see cref="IEvent.Name"/> property.
         /// If multiple <see cref="IEvent.Name"/> are specified, returned events are one of the specified types.
         /// </summary>
-        /// <param name="names">One or more acceptable <see cref="string"/> to filter on. </param
+        /// <param name="names">One or more acceptable <see cref="string"/> to filter on. </param>
```
Comment (szczura) [inline WPF/SeeShells/SeeShells/UI/EventFilters/EventNameFilter.cs]: how did you even notice this lol

Comment (klaki892) [reply WPF/SeeShells/SeeShells/UI/EventFilters/EventNameFilter.cs]: [Resharper ](https://www.jetbrains.com/resharper/)noticed it for me lol
